name: Build with Maven and Java 6

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 1. Set up JDK 6
      uses: actions/setup-java@v3
      with:
        java-version: '6'
        distribution: 'temurin'
        cache: maven
    - name: 2. Download Notes.jar and add it to local maven repository
      run: |
        wget 'https://domino-1.dmytro.cloud/Files.nsf/all/file/$FILE/Notes.jar' -O Notes.jar -q --show-progress
        echo "adding Notes.jar to local maven storage"
        mvn install:install-file -Dfile="Notes.jar" -DgroupId=lotus.notes -DartifactId=notes -Dversion=10.0 -Dpackaging=jar 
    - name: 3. Build with Maven
      run: mvn -B package --file pom.xml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/my-artifact.jar
