name: Build with Maven and Java 6

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 1. Set up Java 6
      uses: actions/setup-java@v1
      with:
        java-version: '6'
        distribution: 'adopt'
    - name: 2. Download Notes.jar and add it to local maven repository
      run: |
        wget 'https://domino-1.dmytro.cloud/Files.nsf/all/file/$FILE/Notes.jar' -O Notes.jar -q --show-progress
        echo "adding Notes.jar to local maven storage"
        mvn install:install-file -Dfile="Notes.jar" -DgroupId=lotus.notes -DartifactId=notes -Dversion=10.0 -Dpackaging=jar 
    - name: 3. Build with Maven
      run: mvn clean install
